"""update job columns

Revision ID: b9be152ace93
Revises: b8baf0faa11d
Create Date: 2026-03-12 17:51:36.423150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9be152ace93'
down_revision: Union[str, Sequence[str], None] = 'b8baf0faa11d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crawl_jobs', 'celery_task_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               schema='docs_mcp')
    op.alter_column('crawl_jobs', 'triggered_by',
               existing_type=sa.VARCHAR(length=32),
               nullable=True,
               schema='docs_mcp')
    op.drop_index(op.f('ix_docs_mcp_crawl_jobs_celery_task_id'), table_name='crawl_jobs', schema='docs_mcp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_docs_mcp_crawl_jobs_celery_task_id'), 'crawl_jobs', ['celery_task_id'], unique=False, schema='docs_mcp')
    op.alter_column('crawl_jobs', 'triggered_by',
               existing_type=sa.VARCHAR(length=32),
               nullable=False,
               schema='docs_mcp')
    op.alter_column('crawl_jobs', 'celery_task_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               schema='docs_mcp')
    # ### end Alembic commands ###
