"""update enum types

Revision ID: b8baf0faa11d
Revises: ad58c2219fa5
Create Date: 2026-03-11 15:21:30.295039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8baf0faa11d'
down_revision: Union[str, Sequence[str], None] = 'ad58c2219fa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crawl_jobs_celery_task_id'), table_name='crawl_jobs', schema='docs_mcp')
    op.drop_index(op.f('ix_crawl_jobs_source_id'), table_name='crawl_jobs', schema='docs_mcp')
    op.create_index(op.f('ix_docs_mcp_crawl_jobs_celery_task_id'), 'crawl_jobs', ['celery_task_id'], unique=False, schema='docs_mcp')
    op.create_index(op.f('ix_docs_mcp_crawl_jobs_source_id'), 'crawl_jobs', ['source_id'], unique=False, schema='docs_mcp')
    op.drop_index(op.f('ix_pages_content_hash'), table_name='pages', schema='docs_mcp')
    op.drop_index(op.f('ix_pages_source_id'), table_name='pages', schema='docs_mcp')
    op.create_index(op.f('ix_docs_mcp_pages_content_hash'), 'pages', ['content_hash'], unique=False, schema='docs_mcp')
    op.create_index(op.f('ix_docs_mcp_pages_source_id'), 'pages', ['source_id'], unique=False, schema='docs_mcp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_docs_mcp_pages_source_id'), table_name='pages', schema='docs_mcp')
    op.drop_index(op.f('ix_docs_mcp_pages_content_hash'), table_name='pages', schema='docs_mcp')
    op.create_index(op.f('ix_pages_source_id'), 'pages', ['source_id'], unique=False, schema='docs_mcp')
    op.create_index(op.f('ix_pages_content_hash'), 'pages', ['content_hash'], unique=False, schema='docs_mcp')
    op.drop_index(op.f('ix_docs_mcp_crawl_jobs_source_id'), table_name='crawl_jobs', schema='docs_mcp')
    op.drop_index(op.f('ix_docs_mcp_crawl_jobs_celery_task_id'), table_name='crawl_jobs', schema='docs_mcp')
    op.create_index(op.f('ix_crawl_jobs_source_id'), 'crawl_jobs', ['source_id'], unique=False, schema='docs_mcp')
    op.create_index(op.f('ix_crawl_jobs_celery_task_id'), 'crawl_jobs', ['celery_task_id'], unique=False, schema='docs_mcp')
    # ### end Alembic commands ###
